### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by jruderman** [nota-lang/nota#1]
"The _principle_ question" should be "The _principal_ question"

"as _oppposed_ to a static image" should be "As _opposed_ to a static image"

"To denote a conflict,we reuse" is missing space after comma

" π1​ and π2​ do not conflict" has an extra space before it

"Javascript" should be "JavaScript"

**Comment by willcrichton** [comment]
Thanks for filing all these reports @jruderman! I will tackle the easy ones soon.
