### ISSUE TITLE
Images and Videos

### ISSUE THREAD

**Issue by HagaiHargil** [nota-lang/nota#16]
Hi, I saw the post on HN and this seems like a great fit for my use-case, which is writing white papers and technical experimental reports. However I didn't see a single example of adding an image or a video to a document, and I wondered whether that was possible within Nota's syntax or only via some custom JSX\HTML code.

Thanks and good luck :)

**Comment by willcrichton** [comment]
Hey, you can use the normal set of HTML tags for media. For example:

```
@img[src="/assets/myimage.jpeg"][alt="My image"]
```

**Comment by HagaiHargil** [comment]
Got it, thanks. I must've missed it when reading the docs.

**Comment by willcrichton** [comment]
The docs are very incomplete, so it's likely undocumented. I'm overhauling the syntax right now to be more Markdown-friendly, and then I will add more comprehensive documentation.

**Comment by HagaiHargil** [comment]
Sounds great! I'll watch the repo and wait for the updated syntax.
