### ISSUE TITLE
Nota does not scale well to width of 1024 

### ISSUE THREAD

**Issue by kermitfrog** [nota-lang/nota#21]
Stumbled upon Nota and immediately noticed an issue (that, unfortunately, many websites have). I'll attach a screenshot that shows a part of what https://willcrichton.net/nota/ looks like for me.

As for my setup: When coding (among other things), I prefer to view documentation in my browser on the left side screen, which has a resolution of 1024x1280.

Besides not beeing able to view the whole text without scrolling horizontally, in this part the text left is cut off - so couldn't scroll left to see it even if I wanted.

![20240614_150336](https://github.com/nota-lang/nota/assets/4614573/5d980898-0e56-4f05-ac13-3c323744d842)

**Comment by willcrichton** [comment]
Yes the original Nota demo was not carefully designed for small monitors or phones. It's not very responsive. Future versions of Nota will not have this issue, thanks for pointing it out!
